Add conclude job

diff --git a/.github/workflows/checks_template.yml b/.github/workflows/checks_template.yml
--- a/.github/workflows/checks_template.yml
+++ b/.github/workflows/checks_template.yml
@@ -74,30 +74,43 @@ jobs:
       matrix:
         python-version: ['3.8', '3.9', '3.10', '3.11']
     needs: checks
+    if: always()
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/setup-python@v4
-      with:
-        python-version: ${{ matrix.python-version }}
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Install
-      run: |
-        python -m pip install --upgrade pip
+      - name: Install
+        run: |
+          python -m pip install --upgrade pip
 
-        # Install optuna from optuna master
-        pip install git+https://github.com/optuna/optuna@master
+          # Install optuna from optuna master
+          pip install git+https://github.com/optuna/optuna@master
 
-        pip install --progress-bar off .[test]
-        if [ -f optuna_integration/${{ inputs.integration_name }}/requirements.txt ]; then
-          pip install -r optuna_integration/${{ inputs.integration_name }}/requirements.txt
-        fi
+          pip install --progress-bar off .[test]
+          if [ -f optuna_integration/${{ inputs.integration_name }}/requirements.txt ]; then
+            pip install -r optuna_integration/${{ inputs.integration_name }}/requirements.txt
+          fi
 
-    - name: Extra commands
-      run: |
-        ${{ inputs.extra_cmds }}
+      - name: Extra commands
+        run: |
+          ${{ inputs.extra_cmds }}
 
-    - name: Tests
-      run: |
-        if [ -e tests/${{ inputs.integration_name }} ]; then
-          pytest tests/${{ inputs.integration_name }}
-        fi
+      - name: Tests
+        run: |
+          if [ -e tests/${{ inputs.integration_name }} ]; then
+            pytest tests/${{ inputs.integration_name }}
+          fi
+
+  conclude:
+    runs-on: ubuntu-latest
+    needs: [checks, tests]
+    if: always()
+    steps:
+      - name: Conclude
+        run: |
+          if [ "${{ needs.checks.result }}" != "success" ] || [ "${{ needs.tests.result }}" != "success" ]; then
+            echo "Previous job failed"
+            exit 1
+          fi
